---
  - name: install package
    apt: name={{ item }} state=present
    with_items:
    - mariadb-server
 
  - name: Create database user
    mysql_user: user=oteemo password=12345 priv=*.*:ALL state=present

  - name: Create database
    mysql_db: db=Temidata state=present

