---
  - name: install package
    apt: name={{ item }} state=present
    with_items:
    - mariadb-server
 
  - name: Create database user
    mysql_user: user=oteemo password=Ch@ng3m3! priv=*.*:ALL state=present

  - name: Create database
    mysql_db: db=Ch@ng3m3! state=present

